      - name: "Take disk`s name"
        ansible.builtin.set_fact:
          target_disk: "{{ item.key }}"
          disk_device: "/dev/{{ item.key }}"

      - name: "Formatind disk to ext4"
        ansible.builtin.filesystem:
          fstype: ext4
          dev: "{{ disk_device }}"

      - name: "Update hardware informations"
        ansible.builtin.setup:
          gather_subset:
            - hardware

      - name: "Mounting disk and add information in /etc/fstab"
        ansible.builtin.mount:
          path: "{{ mount_point }}"
          src: "UUID={{ ansible_facts['devices'][target_disk]['links']['uuids'][0] }}"
          fstype: ext4
          opts: defaults
          state: mounted