# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro'

Vagrant.configure("2") do |config|

   # Make VM Client
   config.vm.define "client" do |client|
      client.vm.box = "bento/ubuntu-24.04"
      client.vm.hostname = "client"
      client.vm.box_check_update = false

      client.vm.provider "virtualbox" do |vb|
         vb.name = "Client"
         vb.gui = false
         vb.cpus = "1" 
         vb.memory = "1024"       
      end
   
      client.vm.network "forwarded_port", guest: 22, host: 2202, id: "ssh", host_ip: "127.0.0.1"
      client.vm.network "private_network", ip: "192.168.60.160", adapter: 2, netmask: "255.255.255.0"

      client.vm.synced_folder ".", "/vagrant", disabled: true

      client.vm.provision "ansible" do |ansible|
        ansible.become = "true"
        ansible.verbose = "v"
        ansible.playbook = "Provisioning/client.yml"
      end

     # client.vm.provision "shell", inline: <<-SHELL
     #   apt-get update
     #   apt-get install -y apache2
     # SHELL
   end

   # Make VM BackUp
   config.vm.define "backup" do |backup|
      backup.vm.box = "bento/ubuntu-24.04"
      backup.vm.hostname = "backup"
      backup.vm.box_check_update = false

      backup.vm.disk :disk, size: "2GB", name: "backup_disk"


      backup.vm.provider "virtualbox" do |vb|
         vb.name = "BackUp"
         vb.gui = false
         vb.cpus = "2" 
         vb.memory = "2048"       
      end

      backup.vm.network "forwarded_port", guest: 22, host: 2201, id: "ssh", host_ip: "127.0.0.1"
      backup.vm.network "private_network", ip: "192.168.60.150", adapter: 2, netmask: "255.255.255.0"

      backup.vm.synced_folder ".", "/vagrant", disabled: true

      backup.vm.provision "ansible" do |ansible|
         ansible.become = "true"
         ansible.verbose = "v"
         ansible.playbook = "Provisioning/backup.yml"
      end

      # backup.vm.provision "shell", inline: <<-SHELL
      #   apt-get update
      #   apt-get install -y apache2
      # SHELL
   end

end