# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_SERVER_URL'] = 'https://elab.pro'

MACHINES = {
  :INetRouter => {
        :box_name => "bento/ubuntu-24.04",
        :net => [
                   {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "ext-net"},
                ]
  },
  :CentralRouter => {
        :box_name => "bento/ubuntu-24.04",
        :net => [
                   {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "ext-net"},
                   {ip: '192.168.255.17', adapter: 3, netmask: "255.255.255.248", virtualbox__intnet: "int-net"},
                   {ip: '192.168.0.1', adapter: 4, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                   {ip: '192.168.0.33', adapter: 5, netmask: "255.255.255.240", virtualbox__intnet: "hw-net"},
                   {ip: '192.168.0.65', adapter: 6, netmask: "255.255.255.192", virtualbox__intnet: "wifi-net"},
                ]
  },

  :Office1Router => {
        :box_name => "bento/ubuntu-24.04",
        :net => [
                   {ip: '192.168.255.18', adapter: 2, netmask: "255.255.255.248", virtualbox__intnet: "int-net"},
                   {ip: '192.168.2.1', adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "dev1-net"},
                   {ip: '192.168.2.65', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "test1-net"},
                   {ip: '192.168.2.129', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "mgt1-net"},
                   {ip: '192.168.2.193', adapter: 6, netmask: "255.255.255.192", virtualbox__intnet: "hw1-net"},
                ]
  },
  
  :Office2Router => {
        :box_name => "bento/ubuntu-24.04",
        :net => [
                   {ip: '192.168.255.19', adapter: 2, netmask: "255.255.255.248", virtualbox__intnet: "int-net"},
                   {ip: '192.168.1.1', adapter: 3, netmask: "255.255.255.128", virtualbox__intnet: "dev2-net"},
                   {ip: '192.168.1.129', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "test2-net"},
                   {ip: '192.168.1.193', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "hw2-net"},
                ]
  },

  :CentralServer => {
        :box_name => "bento/ubuntu-24.04",
        :net => [
                   {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                ]
  },

  :Office1Server => {
        :box_name => "bento/ubuntu-24.04",
        :net => [
                   {ip: '192.168.2.2', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "dev1-net"},
                ]
  },

  :Office2Server => {
        :box_name => "bento/ubuntu-24.04",
        :net => [
                   {ip: '192.168.1.2', adapter: 2, netmask: "255.255.255.128", virtualbox__intnet: "dev2-net"},
                ]
  },
  
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

	box.vm.provider "virtualbox" do |vb|
          vb.name = boxname.to_s
        end

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", **ipconf
        end

#        if boxconfig.key?(:public)
#          box.vm.network "public_network", **boxconfig[:public]
#        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL

        target_servers = ["CentralServer", "Office1Server", "Office2Server"]
        if target_servers.include?(boxname.to_s)
          box.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "Provisioning/playbook.yml"
          end
        end

        case boxname.to_s
        when "INetRouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sysctl net.ipv4.conf.all.forwarding=1
            ip route add 192.168.0.0/22 via 192.168.255.2
            iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
          SHELL
        
        when "CentralRouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sysctl net.ipv4.conf.all.forwarding=1
	    ip route add 192.168.2.0/24 via 192.168.255.18
            ip route add 192.168.1.0/24 via 192.168.255.19
            ip route del default
            ip route add default via 192.168.255.1 metric 10
          SHELL

        when "Office1Router"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sysctl net.ipv4.conf.all.forwarding=1
            ip route del default
            ip route add default via 192.168.255.17 metric 10
          SHELL

        when "Office2Router"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sysctl net.ipv4.conf.all.forwarding=1
            ip route del default
            ip route add default via 192.168.255.17 metric 10
          SHELL
        
        when "CentralServer"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            ip route del default
            ip route add default via 192.168.0.1 metric 10
          SHELL

        when "Office1Server"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            ip route del default
            ip route add default via 192.168.2.1 metric 10
          SHELL

        when "Office2Server"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            ip route del default
            ip route add default via 192.168.1.1 metric 10
          SHELL
        end
    end
  end
end
