frr version 10.7.0
frr defaults traditional
!
hostname router1
log syslog informational
no ipv6 forwarding
!service integrated-vtysh-config

interface eth1
   description router1-2
   ip address 10.0.10.2/30
   ip ospf mtu-ignore
   ip ospf cost 10
   ip ospf hello-interval 10
   ip ospf dead-interval 30
!
interface eth2
   description router2-3
   ip address 10.0.20.1/30
   ip ospf mtu-ignore
   ip ospf cost 10
   ip ospf hello-interval 10
   ip ospf dead-interval 30
!
interface eth3
   description office2
   ip address 192.168.20.1/24
   ip ospf mtu-ignore
   ip ospf cost 10
   ip ospf hello-interval 10
   ip ospf dead-interval 30 
!
router ospf
   router-id 192.168.20.1
   network 10.0.10.0/30 area 0
   network 10.0.20.0/30 area 0
   network 192.168.20.0/24 area 0
   passive-interface eth3 
   neighbor 10.0.10.1
   neighbor 10.0.20.2
   default-information originate always
!
log file /var/log/frr/frr.log