# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_SERVER_URL'] = 'https://elab.pro'

MACHINES = {
  :Router1 => {
        :box_name => "bento/ubuntu-24.04",
        :net => [
                   {ip: '10.0.10.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router12"},
                   {ip: '10.0.30.2', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "router13"},
                   {ip: '192.168.10.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "office1"},
                ]
  },

  :Router2 => {
        :box_name => "bento/ubuntu-24.04",
        :net => [
                   {ip: '10.0.20.1', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "router23"},
	           {ip: '10.0.10.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router12"},
                   {ip: '192.168.20.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "office2"},
                ]
  },
  
  :Router3 => {
        :box_name => "bento/ubuntu-24.04",
        :net => [
                   {ip: '10.0.30.1', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "router13"},
	           {ip: '10.0.20.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router23"},
                   {ip: '192.168.30.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "office3"},
                ]
  },

  :Office1 => {
        :box_name => "bento/ubuntu-24.04",
        :net => [
                   {ip: '192.168.10.10', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "office1"},
                ]
  },

  :Office2 => {
        :box_name => "bento/ubuntu-24.04",
        :net => [
                   {ip: '192.168.20.10', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "office2"},
                ]
  },
  
  :Office3 => {
        :box_name => "bento/ubuntu-24.04",
        :net => [
                   {ip: '192.168.30.10', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "office3"},
                ]
  },

}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

	box.vm.provider "virtualbox" do |vb|
          vb.name = boxname.to_s
        end

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", **ipconf
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL

        target_servers = ["Router1", "Router2", "Router3"]
        if target_servers.include?(boxname.to_s)
          box.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "Provisioning/router.yml"
          end
        end

        target_servers = ["Office1", "Office2", "Office3"]
        if target_servers.include?(boxname.to_s)
          box.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "Provisioning/office.yml"
          end
        end

        case boxname.to_s
        when "Office1"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            ip route del default
            ip route add default via 192.168.10.1
          SHELL
        
        when "Office2"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            ip route del default
            ip route add default via 192.168.20.1
          SHELL

        when "Office3"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            ip route del default
            ip route add default via 192.168.30.1
          SHELL

        end
    end
  end
end
